name: Jalankan ME-CLI

on:
  workflow_dispatch:

jobs:
  run-mecli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Jalankan ME-CLI
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "API_KEY=$API_KEY" > .env
        python main.py
