name: Python CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Ini agar Anda bisa menjalankannya manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Sesuaikan versi python jika perlu

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        API_KEY: ${{ secrets.API_KEY}}
      run: |
        echo "API_KEY=0efe7a4b-e3db-4bba-9d10-c043b213e8ab">.env
        python main.py
